services:
  mysqldb:
    image: mysql:5.7.42
    environment:
      - MYSQL_DATABASE=userdb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '54321:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  app:
    image: digi-cert-task
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/userdb?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - '23232:8080'
    depends_on:
      mysqldb:
        condition: service_healthy